apiVersion: v1
kind: Pod
metadata:
 name: hello-world-app
 labels:
  name: hello-world-app
spec:
  containers:
  - name: localhost
    image: localhost:5000/hello-world-image
    ports:
    - containerPort: 3000